# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  ImageName: 'umakanth455/customerapi:$(Build.BuildId)'

stages:
  - stage: Build
    displayName : Build and Push Docker image
    jobs:
    - job: Build
      displayName: Build and Push Image
      steps:
        
        - task: Docker@2
          inputs:
            containerRegistry: 'DockerSVC'
            repository: 'customerapi'
            command: 'buildAndPush'
            Dockerfile: '**/CustomerApi/CustomerApi/Dockerfile'
            buildContext: 'CustomerApi'
            tags: |
              $(tag)
  
